appsite/urls.py
from django.urls import path
from . import views
from .views import Index_ListView, GameNew_ListView, GameDetailView, OpinionUpdateView
from appsite import views as appsite_views

urlpatterns = [
    #path('', appsite_views.index_view, name='appsite-index'),
    path('', Index_ListView.as_view(), name='appsite-index'), 
    path('newgames/', GameNew_ListView.as_view(), name='appsite-newgames'),
    path('game/<int:pk>/', GameDetailView.as_view(), name='appsite-game_detail'),
    path('game/<int:pk>/update/', appsite_views.OpinionUpdateView, name='appsite-opinion_update'),
    path('game/<int:pk>/delete/', appsite_views.OpinionDeleteView, name='appsite-opinion_delete'),
]

blog/urls.py
from django.urls import path
from . import views
from .views import PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, UserPostListView, GenrePostListView, CommentUpdateView, CommentDeleteView

urlpatterns = [
    path('', PostListView.as_view(), name='blog-blog'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='blog-post_detail'),
    path('post/new/', PostCreateView.as_view(), name='blog-post_create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='blog-post_update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='blog-post_delete'),
    path('post/user/<str:username>/', UserPostListView.as_view(), name='blog-user_posts'),
    path('post/genre/<str:genre>/', GenrePostListView.as_view(), name='blog-genre_posts'),
    path('post/<int:pk>/comment/update/', CommentUpdateView, name='blog-post_comment_update'),
    path('post/<int:pk>/comment/delete/', CommentDeleteView, name='blog-post_comment_delete')
]

gamingwebapp/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from users import views as user_views
from django.contrib.auth import views as auth_views
from appsite import views as appsite_views
from django.conf import settings 
from django.conf.urls.static import static 
from users.views import Keys_ListView

urlpatterns = [
    path('', include('appsite.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('search/', appsite_views.search_game_queryset, name='search_results'),
    path('partyroom/', appsite_views.partyroom_view, name='appsite-partyroom'),
    path('terms/', user_views.terms_view, name='terms'),
    path('faq/', user_views.faq_view, name='faq'),

    path('cart/', appsite_views.cart_view, name='cart'),
    path('cart/<int:id>/update/>', appsite_views.update_cart_view, name='update_cart'),
    path('cart/<int:id>/purchase/', appsite_views.purchase_cart_view, name='purchase_cart'),

    path('register/', user_views.register_view, name='register'),
    path('profile/', user_views.profile_view, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    path('register/seller/', user_views.register_seller_view, name='register_seller'),
    path('seller/', user_views.seller_view, name='sellkey'),
    path('user/keys/', Keys_ListView.as_view(), name='keys'),

    re_path(r'^daguerre/', include('daguerre.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG: #Only on development
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Manually serving static files urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

appsite/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image

REGION_CHOICES = (
    ("1", "EU"),
    ("2", "RU")
)

class Genre(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

"""
class Platform(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name
"""

class Game(models.Model):
    name = models.CharField(max_length=50)
    short_desc = models.CharField(max_length=500, default='')
    long_desc = models.CharField(max_length=10000, default='')
    image = models.ImageField(upload_to='game_pics', null=False)
    banner_img = models.ImageField(upload_to='game_pics', null=False)
    stock = models.IntegerField(default=0)
    release_date = models.DateTimeField(default=timezone.now)
    new_game = models.BooleanField(default=True)
    lowest_price = models.IntegerField(null=True, blank=True)
    languages = models.CharField(max_length=200, default='ES')
    system_requirements = models.CharField(max_length=500)
    genres = models.ManyToManyField(Genre)

    def __str__(self):
        return self.name

class Key(models.Model):
    id = models.AutoField(primary_key=True)
    key_value = models.CharField(max_length=17, unique=True)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    price = models.IntegerField(null=True)
    region = models.CharField(max_length=50, choices = REGION_CHOICES)
    seller = models.ForeignKey('users.Seller', on_delete=models.CASCADE)
    used = models.BooleanField(default=False)
    owner = models.ForeignKey('users.Client', default=None, blank=False, null=False, on_delete=models.CASCADE)
    #platforms = models.ManyToManyField(Platform)
    
    class Meta:
        ordering = ['-price']

    def __str__(self):
        return f'Key for Game {self.game}'


class Shopping_cart(models.Model):
    id = models.AutoField(primary_key=True)
    client = models.OneToOneField('users.Client', on_delete=models.CASCADE)
    keys = models.ManyToManyField(Key)

    def __str__(self):
        return self.client.user.username

class Opinion(models.Model):
    client = models.ForeignKey('users.Client', on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    opinion = models.CharField(max_length=1000)
    date_posted = models.DateTimeField(default=timezone.now)

    class Meta:
        unique_together = ['client', 'game']
        ordering = ['-date_posted']

    def __str__(self):
        return f'From {self.client.user.username} to {self.game.name}' 

"""
class Article_on_shopping_cart(models.Model):
    cart = models.ForeignKey(Shopping_cart, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
"""

appsite/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core import validators
from django.core.exceptions import ValidationError, NON_FIELD_ERRORS
from django.core.validators import RegexValidator
from django.forms import widgets
from .models import Opinion

class OpinionForm(forms.ModelForm):
    opinion = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Opinion 
        fields = ['opinion']

appsite/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect, Http404, HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
import os
from operator import attrgetter
from django.contrib import messages

from .models import Game, Shopping_cart, Key, Opinion, Genre
from .forms import OpinionForm

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import FormView
from django.views.generic.edit import FormMixin
from django.contrib.auth.models import User
from django.db.models import Count, Min, Sum, Avg, Q
from django.db import IntegrityError
"""
#Function to return a list with the games found in the query
def get_game_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    
    for q in queries:
        games = Game.objects.filter(stock__gte=1).filter(Q(name__icontains=q) ).distinct()

        for game in games:
            queryset.append(game)
    return list(set(queryset))
"""
#Function to return a list with the games found in the query
def get_game_queryset(query=None):
    queryset = []
    queries = query.split(" ")
    genres = Genre.objects.all()
    aux=False
    genre = None

    for q in queries:
        for auxgenre in genres:
            if q.upper()==auxgenre.name.upper():
                aux=True
                genre = Genre.objects.filter(name=q.capitalize()).first()

    for q in queries:
        if aux==True:
            games = Game.objects.filter(stock__gte=1).filter(genres=genre).distinct()
            for game in games:
                queryset.append(game)
        else:
            games = Game.objects.filter(stock__gte=1).filter(Q(name__icontains=q)).distinct()
            for game in games:
                queryset.append(game)
    
    return list(set(queryset))

#View to show the games matching the query
def search_game_queryset(request):
    context = {}
    query = ""
    if request.GET:
        query = request.GET['q']
        context['query'] = str(query)

    try: #Searching for name
        games = sorted(get_game_queryset(query), key=attrgetter('name'), reverse=True)
        context['games'] = games
    except: #Searching for genre
        games = sorted(get_game_queryset(query), reverse=True)
        context['games'] = games

    return render(request, "appsite/search.html", context)

#Index view
"""
def index_view(request):
    context = {}

    new_games = Game.objects.filter(new_game=True).filter(stock__gte=1)
    context['new_games'] = new_games

    games = Game.objects.filter(stock__gte=1)
    context['games'] = games

    return render(request, "appsite/index.html", context)
"""

class Index_ListView(ListView):
    model = Game 
    template_name = 'appsite/index.html' # <app>/<model>_<viewtype>.html
    context_object_name = 'games'
    paginate_by = 8

    def get_queryset(self):
        return Game.objects.filter(stock__gte=1)

    def get_context_data(self, **kwargs):
        context = super(Index_ListView, self).get_context_data(**kwargs)
        context['new_games'] = Game.objects.filter(new_game=True).filter(stock__gte=1)
        return context

@login_required
def cart_view(request):
    my_cart = Shopping_cart.objects.get(pk=request.user.id)
    items = my_cart.keys.all()

    context = {
        "games": items,
        "quantity": items.count()
    }
    return render(request, "appsite/cart.html", context)

@login_required
def update_cart_view(request, id):
    my_cart = Shopping_cart.objects.get(pk=request.user.id)

    try:
        item = Key.objects.get(id=id)
    except Key.DoesNotExist:
        pass
    except:
        pass

    if not item in my_cart.keys.all():
        my_cart.keys.add(item)
    else:
        my_cart.keys.remove(item)

    return redirect('cart')

@login_required
def purchase_cart_view(request, id):
    my_cart = Shopping_cart.objects.get(pk=request.user.id)
    items = my_cart.keys.all()
    
    try:
        for item in items:
            #Update Key
            item.owner = request.user.client
            item.used = True
            item.save()

            #Update Game of the key
            item.game.stock -= 1
            try:
                item.game.lowest_price = Key.objects.filter(game_id=item.game.id).filter(used=False).order_by('price').first().price
            except:
                item.game.lowest_price = None
            
            item.game.save()

            #Remove the key from the cart
            my_cart.keys.remove(item)
    except Key.DoesNotExist:
        pass
    except:
        return HttpResponseForbidden()

    return redirect('profile')

class GameNew_ListView(ListView):
    model = Game 
    template_name = 'appsite/newgames.html' # <app>/<model>_<viewtype>.html
    context_object_name = 'games'
    paginate_by = 8

    def get_queryset(self):
        return Game.objects.filter(stock__gte=1).filter(new_game=True)

class GameDetailView(FormMixin, DetailView):
    model = Game
    form_class = OpinionForm

    def get_context_data(self, **kwargs):
        context = super(GameDetailView, self).get_context_data(**kwargs)
        context['lower_key'] = Key.objects.filter(game_id=self.object.id).filter(used=False).order_by('price').first()
        context['keys'] = Key.objects.filter(game_id=self.object.id).filter(used=False).order_by('price')
        #context['opinions'] = Opinion.objects.filter(game_id=self.object.id)

        if self.request.user.is_authenticated:
            opinion = Opinion.objects.filter(client=self.request.user.client).filter(game_id=self.object.id)
            if opinion.exists():
                context['opinion_bool'] = True
            else:
                context['opinion_bool'] = False
        else:
            context['opinion_bool'] = True

        context['form'] = OpinionForm() #initial={'game': self.object, 'client': self.request.user.client}
        return context
    
    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return HttpResponseForbidden()
        self.object = self.get_object()
        form = self.get_form()
        form.instance.client = self.request.user.client
        form.instance.game = self.object
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        try:
            form.save()
        except IntegrityError:
            messages.error(self.request, f'Your have already commented on this game')
        except:
            return HttpResponseForbidden()
        
        return super(GameDetailView, self).form_valid(form)

    def get_success_url(self):
        return reverse('appsite-game_detail', kwargs={'pk': self.object.pk})

def partyroom_view(request):
    return render(request, "appsite/partyroom.html")

def OpinionUpdateView(request, pk):
    opinion = Opinion.objects.filter(client=request.user.client).filter(game_id=pk).first()
    form = OpinionForm(request.POST, initial={'opinion': opinion.opinion}, instance=opinion)
    form.fields['opinion'].initial = opinion.opinion
    form['opinion'].value()
    if form.is_valid():
        form.save()
        return redirect('appsite-index')
    else: 
        print("Invalid form")
        print(form.errors.as_json())
   
    context = {
        'form': form
    }

    return render(request, 'appsite/game_detail_update.html', context)

def OpinionDeleteView(request, pk):
    opinion = Opinion.objects.filter(client=request.user.client).filter(game_id=pk).first().delete()
    return redirect('appsite-index')

appsite/templates/appsite/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    
    <!-- MDB icon -->
    <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon" />
    <!-- Font Awesome -->
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.11.2/css/all.css"
    />
    <!-- Google Fonts Roboto -->
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
    />
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'appsite/css/bootstrap.min.css' %}" />
    <!-- Material Design Bootstrap -->
    <link rel="stylesheet" href="{% static 'appsite/css/mdb.min.css' %}" />
    <!-- Your custom styles (optional) -->
    <link rel="stylesheet" href="{% static 'appsite/css/style.css' %}" />
  </head>
  <body class="elegant-color white-text">
    
    {% include 'includes/navbar.html' %}

    <!--<div class="container" style="background-image: url({% static "appsite/background.png" %});">-->
      <!--<div class="view" style="background-image: url('{% static 'appsite/img/background.png' %}')"></div>-->
        <!-- Mask & flexbox options-->
        <div class="mask rgba-gradient align-items-center">
          <!-- Content -->
          <div style="min-height: 100vh;" class="container animated fadeIn">
        
            {% block body %}{% endblock %}

          </div>
          <!-- Content -->
        </div>
        <!-- Mask & flexbox options-->
     
      <!-- Full Page Intro -->
    <!-- Main navigation -->
    <!-- Main Layout-->

    {% include 'includes/footer.html' %}

    <!-- jQuery -->
    <script type="text/javascript" src="{% static 'appsite/js/jquery.min.js' %}"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="{% static 'appsite/js/popper.min.js' %}"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="{% static 'appsite/js/bootstrap.min.js' %}"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="{% static 'appsite/js/mdb.min.js' %}"></script>

    <!-- Your custom scripts (optional) -->
    <script type="text/javascript"></script>

    <script type="text/javascript">
      new WOW().init();
    </script>

  </body>
</html>

appsite/templates/appsite/game_detail.html
{% extends "appsite/base.html" %}
{% load static %}
{% load daguerre %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


{% block title %}
    Gaming webapp
{% endblock %}

{% block body %}

<div class="container my-5 py-5 z-depth-1">

    <!--Section: Content-->
    <section class="text-center">
      {% include 'includes/alert.html' %}
      <div class="row">
  
        <div class="col-lg-4">
          <img src="{% adjust object.image 'fit' width=300 height=400 %}" />  
        </div>
  
        <div class="col-lg-4 text-center text-md-left">
          <span>for Steam</span>
          <h1 class="h1-responsive text-center text-md-left product-name font-weight-bold dark-grey-text mb-1 ml-xl-0 ml-4">
            {{ object.name }}
          </h1>
          {% if object.new_game == True %}
            <span class="badge badge-danger product mb-4 ml-xl-0 ml-4">New</span>
          {% endif %}
          <div>
            {% for genre in object.genres.all %}
              {{ genre }}, 
            {% endfor %}
          </div>
          <p class="white-text pt-5">{{ object.short_desc }}</p>
        </div>

        <div class="col-lg-4 text-center text-md-left">
          <!-- Card -->
          <div class="card mb-4">

            <!--Card image-->
            <div class="view overlay"> 
              <img class="rounded-circle card-img-top w-25 m-2 d-flex float-left" src="{% adjust lower_key.seller.client.user.profile.image 'fit' width=150 height=70 %}"  alt="avatar image">
              <h4 class=" h4-responsive mt-2">{{ lower_key.seller.client.user.username }}</h4>
              {% include 'includes/rating_stars.html' with object=lower_key.seller %}
            </div>

            <!--Card content-->
            <div class="card-body">

              <!--Title-->
              <h4 class="card-title"></h4>
              <div class="p-4"></div>
              <!--Text-->
              <span class="text-muted m-0">Price</span>
              <h1 class="h1-responsive text-center text-md-left mb-1 ml-xl-0 ml-1 mt-0">
                <span class="white-text mt-0">
                    {{ object.lowest_price }} €
                </span>
              </h1>
              <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
              
              <div class="col-md-12 p-0">
                  <a href="{% url 'update_cart' lower_key.id %}" class="btn btn-primary btn-rounded w-100 p-3">
                      <i class="fas fa-cart-plus mr-2" aria-hidden="true"></i> Add to cart
                  </a> 
              </div>
            </div>

          </div>
          <!-- Card -->
        </div>
      </div>

      <div class="row pt-2">
        <!-- Classic tabs -->
        <div class="classic-tabs mx-2  w-100">

          <ul class="nav tabs-orange" id="myClassicTabShadow" role="tablist">
            <li class="nav-item">
              <a class="nav-link  waves-light active show" id="offers-tab-classic-shadow" data-toggle="tab" href="#offers-classic-shadow"
                role="tab" aria-controls="offers-classic-shadow" aria-selected="true">Offers</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-light" id="gd-tab-classic-shadow" data-toggle="tab" href="#gd-classic-shadow"
                role="tab" aria-controls="gd-classic-shadow" aria-selected="false">Game Description</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-light" id="sr-tab-classic-shadow" data-toggle="tab" href="#sr-classic-shadow"
                role="tab" aria-controls="sr-classic-shadow" aria-selected="false">System Requirements</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-light" id="language-tab-classic-shadow" data-toggle="tab" href="#language-classic-shadow"
                role="tab" aria-controls="language-classic-shadow" aria-selected="false">Languages</a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-light" id="opinion-tab-classic-shadow" data-toggle="tab" href="#opinion-classic-shadow"
                role="tab" aria-controls="opinion-classic-shadow" aria-selected="false">Opinions</a>
            </li>
          </ul>

          <div class="tab-content card" id="myClassicTabContentShadow">
            <div class="tab-pane fade active show " id="offers-classic-shadow" role="tabpanel" aria-labelledby="offers-tab-classic-shadow">

              <ul class="list-unstyled">
                {% for key in keys %}
                  <li class="media m-2 clearfix ">
                    <img class="d-flex mr-3 float-left rounded-circle" src="{% adjust key.seller.client.user.profile.image 'fit' width=150 height=70 %}">
                    <div class="d-block float-left">
                      <h5 class="mt-0 mb-2 font-weight-bold">{{ key.seller.client.user.username }}</h5>
                      {% include 'includes/rating_stars.html' with object=key.seller %}
                    </div>
                    <div class="media-body">
                      <div class="col-md-12 text-center text-md-left text-md-right float-right">
                        <a href="{% url 'update_cart' key.id %}" class="btn btn-primary btn-rounded float-right">
                          <i class="fas fa-cart-plus" aria-hidden="true"></i> Add to cart
                        </a> 
                        <p class="text-muted h1 m-2 float-right"> {{ key.price }} € </p>
                      </div>
                    </div>
                  </li>
                {% endfor %}
              </ul>
            </div>
            <div class="tab-pane fade" id="gd-classic-shadow" role="tabpanel" aria-labelledby="gd-tab-classic-shadow">
              <p class="pt-3">{{ object.long_desc }}</p>
            </div>
            <div class="tab-pane fade" id="sr-classic-shadow" role="tabpanel" aria-labelledby="sr-tab-classic-shadow">
              <p class="pt-3">{{ object.system_requirements }}</p>
            </div>
            <div class="tab-pane fade" id="language-classic-shadow" role="tabpanel" aria-labelledby="language-tab-classic-shadow">
              <p class="pt-3">{{ object.languages }}</p>
            </div>
            <div class="tab-pane fade" id="opinion-classic-shadow" role="tabpanel" aria-labelledby="opinion-tab-classic-shadow">
              <ul class="list-unstyled">
                {% if user.is_authenticated %}
                  {% if opinion_bool == False %}
                    <li class="media m-2">
                      <div class="d-block">
                        <div class="row">
                          <div class="col">
                            <img class="d-flex  ml-1 mr-3 card-img-100 rounded-circle z-depth-1-half" src="{% adjust user.profile.image 'fit' width=150 height=70 %}">
                            <h5 class="user-name mt-1 mb-2 font-weight-bold">{{ user.username }}</h5>
                          </div>
                          <div class="col d-flex align-items-center">
                            <form method="POST" action="">
                              {% csrf_token %}
                            <button class="btn btn-info btn-sm " type="submit">Post</button>
                          </div>
                        </div>
                      </div>
                      <div class="media-body">
                        <div class="w-responsive text-center mx-auto p-3 mt-2">
                          {% render_field form.opinion class="d-flex form-control" rows="3" %}  
                        </form>
                        </div>
                      </div>
                    </li>
                  {% endif %}
                {% endif %}
                {% for opinion in object.opinion_set.all %}
                  <li class="media m-2 clearfix">
                    <img class="d-flex mr-3 float-left card-img-100 rounded-circle z-depth-1-half" src="{% adjust opinion.client.user.profile.image 'fit' width=150 height=70 %}">
                    <div class="d-block float-left">
                      <h5 class="user-name mt-0 mb-2 font-weight-bold">{{ opinion.client.user.username }}</h5>
                      {% include 'includes/rating_stars.html' with object=opinion.client.seller %}
                      <div class="card-data">
                        <ul class="list-unstyled mb-1">
                          <li class="comment-date font-small grey-text">
                            <i class="far fa-clock"></i>{{ opinion.date_posted|date:'F d, Y' }} </li>
                        </ul>
                      </div>
                    </div>
                    <div class="media-body">
                      <p class="white-text article p-3">{{ opinion.opinion }}</p>
                      {% if user.is_authenticated %}
                        {% if opinion.client == user.client %}
                          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'appsite-opinion_update' object.id %}">EDIT</a>
                          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'appsite-opinion_delete' object.id %}">Delete</a>
                        {% endif %}
                      {% endif %}
                    </div>
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>

        </div>
        <!-- Classic tabs -->
      </div>

     
  
    </section>
    <!--Section: Content-->
  
  
</div>
    
{% endblock %}

appsite/templates/appsite/game_detail_update.html
{% extends "appsite/base.html" %}
{% load static %}
{% load daguerre %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


{% block title %}
    Gaming webapp
{% endblock %}

{% block body %}

<div class="container my-5 py-5 z-depth-1">

    <!--Section: Content-->
    <section class="text-center">
      {% include 'includes/alert.html' %}
      <div class="row">
            {% if user.is_authenticated %}
                  <div class="d-block">
                    <div class="row">
                      <div class="col">
                        <img class="d-flex  ml-1 mr-3 card-img-100 rounded-circle z-depth-1-half" src="{{ user.profile.avatar.url }}" alt="Generic placeholder image">
                        <h5 class="user-name mt-1 mb-2 font-weight-bold">{{ user.username }}</h5>
                      </div>
                      <div class="col d-flex align-items-center">
                        <form method="POST" action="">
                          {% csrf_token %}
                        <button class="btn btn-info btn-sm " type="submit">Post</button>
                      </div>
                    </div>
                  </div>
                  <div class="media-body">
                    <div class="w-responsive text-center mx-auto p-3 mt-2">
                      {% render_field form.opinion class="d-flex form-control" rows="3" %}  
                    </form>
                    </div>
                  </div>
            {% endif %}
      </div>
    </section>
    <!--Section: Content-->
  
  
</div>
    
{% endblock %}

appsite/templates/appsite/modules_sign_up.html
{% extends "appsite/base.html" %}

{% block title %}
    Gaming webapp
{% endblock %}

{% block body %}
<div class="container my-5 py-5 z-depth-1">


    <!--Section: Content-->
    <section class="px-md-5 mx-md-5 text-center text-lg-left dark-grey-text">
 

      <!--Grid row-->
      <div class="row d-flex justify-content-center">

        <!--Grid column-->
        <div class="col-md-6">

          <!-- Default form login -->
          <form class="text-center" action="#!">

            <p class="h4 mb-4">Sign in</p>

            <!-- Email -->
            <input type="email" id="defaultLoginFormEmail" class="form-control mb-4" placeholder="E-mail">
 
            <!-- Password -->
            <input type="password" id="defaultLoginFormPassword" class="form-control mb-4" placeholder="Password">

            <div class="d-flex justify-content-around">
              <div>
                <!-- Remember me -->
                <div class="custom-control custom-checkbox">
                  <input type="checkbox" class="custom-control-input" id="defaultLoginFormRemember">
                  <label class="custom-control-label" for="defaultLoginFormRemember">Remember me</label>
                </div>
              </div>
              <div>
                <!-- Forgot password -->
                <a href="">Forgot password?</a>
              </div>
            </div>

            <!-- Sign in button -->
            <button class="btn btn-info btn-block my-4" type="submit">Sign in</button>

            <!-- Register -->
            <p>Not a member?
              <a href="">Register</a>
            </p>

            <!-- Social login -->
            <p>or sign in with:</p>

                <a href="#" class="mx-1" role="button"><i class="fab fa-facebook-f"></i></a>
                <a href="#" class="mx-1" role="button"><i class="fab fa-twitter"></i></a>
                <a href="#" class="mx-1" role="button"><i class="fab fa-linkedin-in"></i></a>
                <a href="#" class="mx-1" role="button"><i class="fab fa-github"></i></a>

          </form>
          <!-- Default form login -->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->


    </section>
    <!--Section: Content-->


  </div>
{% endblock %}

appsite/templates/appsite/private.html
{% extends "appsite/base.html" %}

{% block title %}
    Gaming webapp
{% endblock %}

{% block body %}
PRIVADA
{% endblock %}